In [0]:
import numpy as np

In [0]:
list_val = [1,2,3,4]

In [3]:
a = np.array(list_val, float)
print(a)

[1. 2. 3. 4.]


In [4]:
list_val = [[1,2,3], [4,5,6]]
a = np.array(list_val, float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
print(a.shape)

(2, 3)


In [6]:
b = a.reshape(3,2)
print(b)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [8]:
print(a[:1])

[[1. 2. 3.]]


In [10]:
print(a[0])

[1. 2. 3.]


In [9]:
print(a[1])

[4. 5. 6.]


In [11]:
print(a[1][0])

4.0


In [12]:
print(a[0][2])

3.0


In [13]:
print(a[0,0])

1.0


In [14]:
print(a[1,2])

6.0


In [15]:
print(a[1:])

[[4. 5. 6.]]


In [16]:
print(a[:,1])

[2. 5.]


In [17]:
print(a[:, 2])

[3. 6.]


In [18]:
print(a.shape)

(2, 3)


In [19]:
a = np.array([1,2,3], float)
print(a)

[1. 2. 3.]


In [21]:
b = a.copy()
print(b)

[1. 2. 3.]


In [22]:
print(b.tolist())

[1.0, 2.0, 3.0]


In [24]:
a.fill(0)
print(a)

[0. 0. 0.]


In [25]:
print(a.transpose())

[0. 0. 0.]


In [27]:
a = np.array([[1,2,3], [4,5,6]], float).reshape(3,2)
print(a)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [28]:
print(a.flatten())

[1. 2. 3. 4. 5. 6.]


In [29]:
print(a)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [34]:
a = np.array([[1,2,3], [8,9,10]], float)
b = np.array([[4,5,6], [11,12,13]], float)
print(np.concatenate((a,b)))

[[ 1.  2.  3.]
 [ 8.  9. 10.]
 [ 4.  5.  6.]
 [11. 12. 13.]]


In [35]:
z = np.zeros(10, float)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
i = np.identity(4, int)
print(i)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [38]:
a = np.array([[1,2,3], [8,9,10]], int)
b = np.array([[4,5,6], [11,12,13]], int)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

[[ 5  7  9]
 [19 21 23]]
[[-3 -3 -3]
 [-3 -3 -3]]
[[  4  10  18]
 [ 88 108 130]]
[[0.25       0.4        0.5       ]
 [0.72727273 0.75       0.76923077]]
[[ 1  2  3]
 [ 8  9 10]]
[[             1             32            729]
 [    8589934592   282429536481 10000000000000]]


In [39]:
print(np.sqrt(b))

[[2.         2.23606798 2.44948974]
 [3.31662479 3.46410162 3.60555128]]


In [40]:
print(np.pi)

3.141592653589793


In [41]:
for x in a:
  print(x)

[1 2 3]
[ 8  9 10]


In [43]:
for (x) in a:
  print(x*x)

[1 4 9]
[ 64  81 100]


In [44]:
print(a.prod())

4320


In [45]:
print(a.sum())

33


In [46]:
print(a.mean())

5.5


In [48]:
print(a.min())
print(a.max())

1
10


In [49]:
print(a.argmin())

0


In [50]:
print(a.argmax())

5


In [51]:
print(a.sort())

None


In [53]:
print(np.unique(a))

[ 1  2  3  8  9 10]
