In [0]:
import numpy as np

In [0]:
a = np.array([1,2,3])

In [0]:
print(a)

[1 2 3]


In [0]:
b = np.array([4,5,6,7,8])

In [0]:
print(b)

[4 5 6 7 8]


In [0]:
c= np.array([1,2,3,4,5,6])
print(c)

[1 2 3 4 5 6]


In [0]:
multi_arr = np.array([[1,2],[4,5]])
print(multi_arr)

[[1 2]
 [4 5]]


In [0]:
multi_arr2 = np.array([[2,3,4], [4,5,6]])
print(multi_arr2)

[[2 3 4]
 [4 5 6]]


In [0]:
res_arr = np.array([[1,2], [7,8]])
print(res_arr)

[[1 2]
 [7 8]]


In [0]:
arr = np.array([1,2,3,4], ndmin=2)
print(arr)

[[1 2 3 4]]


In [0]:
arr_res = np.array([4,5,6], ndmin=1)
print(arr_res)

[4 5 6]


In [0]:
arr_comp = np.array([1,2,3], dtype=complex)
print(arr_comp)

[1.+0.j 2.+0.j 3.+0.j]


In [0]:
dt =np.dtype('>i4')
print(dt)

>i4


In [0]:
dt1 = np.dtype('<i4')
print(dt1)

int32


In [0]:
dt = np.dtype([('age', np.int8)])

In [0]:
arr = np.array([(10,), (2,), (3,)], dtype=dt)
print(arr)

[(10,) ( 2,) ( 3,)]


In [0]:
print(arr['age'])

[10  2  3]


In [0]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape)

(2, 3)


In [0]:
arr.shape = (3,2)
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [0]:
arr.shape = (1,6)
print(arr)

[[1 2 3 4 5 6]]


In [0]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [0]:
print(a.shape)

(2, 3)


In [0]:
b = a.reshape(3,2)
print(b)


[[1 2]
 [3 4]
 [5 6]]


While reshaping, always remember rows * columns = total number of elements
before reshaping and after re-shaping

In [0]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [0]:
b = a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [0]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
print(a.shape)

(10,)


In [0]:
a = np.zeros([2,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [0]:
c = np.ones(10)
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [0]:
c = np.ones([3,3])
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [0]:
arr = (1,2,3,4)
print(np.asarray(arr))

[1 2 3 4]


In [0]:
list1 = range(10)
print(list1)

range(0, 10)


In [0]:
values = iter(list1)
print(values)

In [0]:
x = np.fromiter(values, dtype='int32')
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
print(x.shape)

(10,)


In [0]:
print(x.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [0]:
y = np.arange(1,10,3)
print(y)

[1 4 7]


In [0]:
y = np.arange(0,100, 5)
print(y)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
